default:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker info

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

workflow:
  rules:
    # automatically run pipeline when changes are pushed to `project` branch
    - if: $CI_COMMIT_BRANCH == "project"
      when: always

stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: nikolaik/python-nodejs:latest
  before_script:
    # install dependencies
    - cd monitor && npm ci && cd ..
    - cd service2 && npm ci && cd ..
  script:
    # run linter and build services
    - cd monitor && npm run lint && npm run build && cd ..
    - cd service2 && npm run lint && npm run build && cd ..

tests:
  stage: test
  image: nikolaik/python-nodejs:latest
  before_script:
    # install dependencies
    - cd monitor && npm ci && cd ..
    - cd service2 && npm ci && cd ..
  script:
    # run tests
    - cd monitor && npm run test && cd ..
    - cd service2 && npm run test && cd ..

deploy:
  stage: deploy
  script:
    - docker compose up --build --detach
